# Generated by Django 5.0 on 2025-09-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecipient',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Leído el'),
        ),
    ]
