# Generated by Django 5.0 on 2025-11-12 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_emailrecipient_read_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkemail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mensaje Masivo', 'verbose_name_plural': 'Mensajes Masivos'},
        ),
        migrations.AlterModelOptions(
            name='emailrecipient',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RemoveField(
            model_name='emailrecipient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emailrecipient',
            name='error_message',
        ),
        migrations.AddField(
            model_name='bulkemail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='communications_attachments/', verbose_name='Adjuntar Archivo'),
        ),
        migrations.AlterField(
            model_name='bulkemail',
            name='body_html',
            field=models.TextField(verbose_name='Cuerpo del Mensaje (HTML)'),
        ),
        migrations.AlterField(
            model_name='bulkemail',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bulkemail',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bulkemail',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='bulk_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.bulkemail'),
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='status',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
