# Generated by Django 5.0 on 2025-10-09 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_emailrecipient_read_at'),
        ('players', '0002_remove_player_is_active_player_position_player_rut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkemail',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='bulkemail',
            name='audience',
            field=models.CharField(choices=[('all_guardians', 'Todos los Apoderados'), ('team_guardians', 'Por Equipo'), ('specific_guardians', 'Apoderados Específicos')], default=1, max_length=20, verbose_name='Audiencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulkemail',
            name='message_type',
            field=models.CharField(choices=[('announcement', 'Anuncio'), ('notification', 'Notificación'), ('reminder', 'Recordatorio'), ('emergency', 'Emergencia')], default='notification', max_length=20, verbose_name='Tipo de Mensaje'),
        ),
        migrations.AddField(
            model_name='bulkemail',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado'), ('scheduled', 'Programado')], default='draft', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='bulkemail',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.category', verbose_name='Equipo Destino'),
        ),
    ]
