# Generated by Django 5.0 on 2025-09-11 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_first_name', models.CharField(max_length=50, verbose_name='Nombre del jugador')),
                ('player_last_name', models.CharField(max_length=50, verbose_name='Apellido del jugador')),
                ('player_rut', models.CharField(max_length=12, verbose_name='RUT del jugador')),
                ('player_birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('team', models.CharField(max_length=50, verbose_name='Equipo solicitado')),
                ('emergency_contact', models.CharField(max_length=100, verbose_name='Contacto de emergencia')),
                ('emergency_phone', models.CharField(max_length=20, verbose_name='Teléfono de emergencia')),
                ('medical_info', models.TextField(blank=True, verbose_name='Información médica')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Apoderado')),
            ],
            options={
                'verbose_name': 'Registro de Jugador',
                'verbose_name_plural': 'Registros de Jugadores',
                'ordering': ['-created_at'],
            },
        ),
    ]
