[phases.setup]
nixPkgs = ['python312']

[phases.install]
cmds = [
    'python -m venv --copies /opt/venv',
    '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = '. /opt/venv/bin/activate && gunicorn club.wsgi --log-file -'

[variables]
DISABLE_COLLECTSTATIC = '1'