# Generated by Django 5.0 on 2025-11-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_delete_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas (Nro. Transacción)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(null=True, upload_to='payment_proofs/', verbose_name='Comprobante de Pago'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('atrasada', 'Atrasada'), ('en revisión', 'En Revisión'), ('pagada', 'Pagada')], default='pendiente', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('cheque', 'Cheque')], max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('completado', 'Completado'), ('fallido', 'Rechazado')], default='pendiente', max_length=12, verbose_name='Estado'),
        ),
    ]
