# Generated by Django 5.0 on 2025-10-09 02:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_delete_sponsor'),
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('transaction_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('cuota_jugador', 'Cuota de Jugador'), ('aporte_auspiciador', 'Aporte de Auspiciador'), ('pago_proveedor', 'Pago a Proveedor'), ('venta_entradas', 'Venta de Entradas'), ('gasto_operativo', 'Gasto Operativo'), ('otro_ingreso', 'Otro Ingreso'), ('otro_egreso', 'Otro Egreso')], max_length=30, verbose_name='Categoría')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Transacción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.payment', verbose_name='Pago de Cuota Asociado')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsors.sponsor', verbose_name='Auspiciador Asociado')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
