# Generated by Django 5.0 on 2025-11-10 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_payment_transaction_id_payment_notes_and_more'),
        ('players', '0003_player_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('sponsor', 'Auspiciador'), ('evento', 'Evento'), ('donacion', 'Donación'), ('entrada', 'Entradas'), ('arriendo', 'Arriendo Gimnasio'), ('arbitraje', 'Pago Árbitros'), ('proveedor', 'Pago Proveedores'), ('cuerpo_tecnico', 'Cuerpo Técnico'), ('equipamiento', 'Equipamiento'), ('transporte', 'Transporte'), ('otros', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha de Transacción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player', verbose_name='Jugador (Opcional)')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-date'],
            },
        ),
    ]
