# Generated by Django 5.0 on 2025-11-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedefinition',
            name='period',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('unico', 'Pago Único'), ('anual', 'Anual')], max_length=10, verbose_name='Período'),
        ),
    ]
