# Generated by Django 5.0 on 2025-11-21 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_feedefinition_period'),
        ('sponsors', '0002_remove_sponsor_active_remove_sponsor_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contribution_type',
            field=models.CharField(choices=[('monetary', 'Monetario (Dinero)'), ('goods', 'Implementos / Especies / Servicios')], default='monetary', max_length=10, verbose_name='Tipo de Aporte'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='sponsors.sponsor', verbose_name='Auspiciador (Si aplica)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monto Estimado/Real'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('sponsor', 'Auspiciador'), ('evento', 'Evento'), ('donacion', 'Donación'), ('entrada', 'Entradas'), ('cuota', 'Cuota Social/Deportiva'), ('arriendo', 'Arriendo Gimnasio'), ('arbitraje', 'Pago Árbitros'), ('proveedor', 'Pago Proveedores'), ('cuerpo_tecnico', 'Cuerpo Técnico'), ('equipamiento', 'Equipamiento'), ('transporte', 'Transporte'), ('otros', 'Otros')], max_length=20, verbose_name='Categoría'),
        ),
    ]
