# Generated by Django 5.0 on 2025-11-10 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('event_type', models.CharField(choices=[('partido', 'Partido'), ('novedad', 'Novedad'), ('reunion', 'Reunión'), ('evento', 'Evento')], default='novedad', max_length=10, verbose_name='Tipo de Evento')),
            ],
            options={
                'verbose_name': 'Evento de Landing',
                'verbose_name_plural': 'Eventos del Calendario (Landing)',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LandingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='landing/news/', verbose_name='Imagen (Obligatoria)')),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Etiqueta (Ej: PLAYOFF)')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Párrafo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
            ],
            options={
                'verbose_name': 'Noticia de Landing',
                'verbose_name_plural': 'Noticias de Landing (Máx. 3 se muestran)',
                'ordering': ['-created_at'],
            },
        ),
    ]
