# Generated by Django 5.0 on 2025-09-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auspiciador',
                'verbose_name_plural': 'Auspiciadores',
                'ordering': ['name'],
            },
        ),
    ]
