# Generated by Django 5.0 on 2025-11-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='active',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='url',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de Contacto'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible en la página web'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre Empresa'),
        ),
    ]
