# Generated by Django 5.0 on 2025-09-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('starts_at', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('ends_at', models.DateTimeField(verbose_name='Fecha y hora de fin')),
                ('type', models.CharField(choices=[('entrenamiento', 'Entrenamiento'), ('otro', 'Otro')], max_length=15, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de cumpleaños')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Cumpleaños',
                'verbose_name_plural': 'Cumpleaños',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('opponent', models.CharField(max_length=100, verbose_name='Rival')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('starts_at', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['starts_at'],
            },
        ),
    ]
