# Generated by Django 5.0 on 2025-09-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_active',
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('base', 'Base'), ('escolta', 'Escolta'), ('alero', 'Alero'), ('ala_pivot', 'Ala-Pívot'), ('pivot', 'Pívot')], max_length=20, null=True, verbose_name='Posición'),
        ),
        migrations.AddField(
            model_name='player',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('injured', 'Lesionado')], default='active', max_length=10, verbose_name='Estado'),
        ),
    ]
