# Generated by Django 5.0 on 2025-11-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_is_active_player_position_player_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='¿Jugadora Destacada? (Landing)'),
        ),
    ]
