# Generated by Django 5.0 on 2025-11-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_registration_open',
            field=models.BooleanField(default=False, help_text='Marcar si esta categoría acepta nuevas inscripciones desde la web.', verbose_name='Inscripciones Abiertas'),
        ),
    ]
