# Generated by Django 5.0 on 2025-11-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_category_is_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='association',
            field=models.CharField(blank=True, help_text='Ej: Federación de Básquetbol de Chile', max_length=100, null=True, verbose_name='Asociación/Federación'),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 170.5', max_digits=5, null=True, verbose_name='Estatura (cm)'),
        ),
        migrations.AddField(
            model_name='player',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Alergias, condiciones pre-existentes, lesiones anteriores, etc.', null=True, verbose_name='Condiciones Médicas'),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apodo'),
        ),
        migrations.AddField(
            model_name='player',
            name='permissions_notes',
            field=models.TextField(blank=True, help_text='Notas sobre permisos de imagen, autorizaciones de viaje, etc.', null=True, verbose_name='Permisos y Autorizaciones'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Jugadora'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Jugadora'),
        ),
    ]
